CREATE TABLE user_account (
                              uid         BIGINT PRIMARY KEY,
                              balance     NUMERIC(12, 2) NOT NULL DEFAULT 0,
                              exp         INTEGER        NOT NULL DEFAULT 0,
                              level       INTEGER        NOT NULL DEFAULT 1,
                              status      TEXT           NOT NULL DEFAULT 'active',
                              updated_at  TIMESTAMPTZ    NOT NULL DEFAULT now(),

                              CONSTRAINT fk_user_account_user
                                  FOREIGN KEY (uid)
                                      REFERENCES users(userid)
                                      ON DELETE CASCADE
);


CREATE TABLE user_borrow_records (
                                     id          BIGSERIAL PRIMARY KEY,
                                     uid         BIGINT      NOT NULL,
                                     book_id     BIGINT      NOT NULL,

                                     amount      INTEGER     NOT NULL DEFAULT 1,
                                     CHECK (amount > 0),

                                     borrow_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
                                     due_at      TIMESTAMPTZ NOT NULL,
                                     return_at   TIMESTAMPTZ,

                                     status      TEXT        NOT NULL DEFAULT 'borrowed',
                                     CHECK (status IN ('borrowed', 'returned', 'overdue')),

                                     CONSTRAINT fk_borrow_user
                                         FOREIGN KEY (uid)
                                             REFERENCES users(userid)
                                             ON DELETE CASCADE
);

CREATE INDEX idx_borrow_uid_status
    ON user_borrow_records (uid, status);

CREATE INDEX idx_borrow_uid_borrow_at
    ON user_borrow_records (uid, borrow_at DESC);

CREATE TABLE user_bookshelf (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                uid         BIGINT      NOT NULL,
                                book_id     BIGINT      NOT NULL,
                                created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
                                UNIQUE (uid, book_id),

                                CONSTRAINT fk_bookshelf_user
                                    FOREIGN KEY (uid)
                                        REFERENCES users(userid)
                                        ON DELETE CASCADE
);

CREATE INDEX idx_bookshelf_uid_created_at
    ON user_bookshelf (uid, created_at DESC);



