create table public.user_account
(
    uid        bigint                                          not null
        primary key
        constraint fk_user_account_user
            references public.users (userid)
            on delete cascade,
    balance    numeric(12, 2)           default 0              not null,
    exp        integer                  default 0              not null,
    level      integer                  default 1              not null,
    status     text                     default 'active'::text not null,
    updated_at timestamp with time zone default now()          not null
);

alter table public.user_account
    owner to cybercafe;

create table public.user_bookshelf
(
    id         bigint generated by default as identity,
    uid        bigint                                 not null
        constraint fk_bookshelf_user
            references public.users (userid)
            on delete cascade,
    book_id    bigint                                 not null,
    created_at timestamp with time zone default now() not null,
    unique (uid, book_id)
);

alter table public.user_bookshelf
    owner to cybercafe;

create table public.user_borrow_records
(
    id        bigserial
        primary key,
    uid       bigint                                            not null
        constraint fk_borrow_user
            references public.users (userid)
            on delete cascade,
    book_id   text                                              not null,
    amount    integer                  default 1                not null
        constraint user_borrow_records_amount_check
            check (amount > 0),
    borrow_at timestamp with time zone default now()            not null,
    due_at    timestamp with time zone                          not null,
    return_at timestamp with time zone,
    status    text                     default 'borrowed'::text not null
        constraint user_borrow_records_status_check
            check (status = ANY (ARRAY ['borrowed'::text, 'returned'::text, 'overdue'::text]))
);

alter table public.user_borrow_records
    owner to cybercafe;

create index idx_borrow_uid_status
    on public.user_borrow_records (uid, status);

create index idx_borrow_uid_borrow_at
    on public.user_borrow_records (uid asc, borrow_at desc);

